# Enum is used to define a fixed set of key lifecycle states
from enum import Enum

# datetime utilities for timestamp handling and expiry calculation
from datetime import datetime, timezone, timedelta


# KeyState defines the lifecycle states of a QKD key
# These states are used by the KMS to manage key validity
class KeyState(str, Enum):
    INIT = "INIT"              # Key object created
    RAW = "RAW"                # Raw key generated (before post-processing)
    PROCESSED = "PROCESSED"    # Key processed (sifting + filtering + amplification)
    STORED = "STORED"          # Final key stored at Remote KMS
    CONSUMED = "CONSUMED"      # Key used by an application
    EXPIRED = "EXPIRED"        # Key expired due to TTL


# Key class represents a single cryptographic key in the QKD system
class Key:
    def __init__(self, key_id, raw_key_value, key_size, created_at, ttl_seconds):
        """
        Initialize a Key object with metadata required for lifecycle tracking.
        """

        # Unique identifier for the key (used for tracking and auditing)
        self.key_id = key_id

        # Raw key material generated by the emulation layer
        # This represents the output of the QKD source (before processing)
        self.raw_key_value = raw_key_value

        # Final key material after post-processing
        # This will be set later in the pipeline
        self.processed_key_value = None

        # Size of the key in bits (e.g., 128 or 256)
        self.key_size = key_size

        # Original creation timestamp of the key
        # Parsed from ISO format string sent by Local KMS
        self.created_at = datetime.fromisoformat(created_at)

        # Time-to-live (TTL) of the key expressed as a time duration
        self.ttl = timedelta(seconds=ttl_seconds)

        # Initial lifecycle state
        self.state = KeyState.RAW

    def is_expired(self):
        """
        Check whether the key has exceeded its allowed lifetime.
        """

        # Compare current UTC time with (creation time + TTL)
        # If current time is greater, the key is considered expired
        return datetime.now(timezone.utc) > self.created_at + self.ttl
